Add option to return none on unknown union variants
palantir/conjure-python-client pull request #150
Opened 2023-05-03 00:02 UTC by markgrex

## Before this PR
See https://github.com/palantir/conjure-python-client/issues/129

## After this PR
This PR adds a flag, that when set to true, changes the deserialization behavior to to return `None` instead of throwing an exception on encountering an unknown union variant. This flag is optional, and is set to false by default.

Once this PR merges, we can update the code generation in [conjure-python](https://github.com/palantir/conjure-python/blob/3b549429824b9ea2511d98d6596a385b0ba86ebd/conjure-python-core/src/main/java/com/palantir/conjure/python/poet/PythonEndpointDefinition.java#L233) to pass through this flag to `ConjureDecoder`.

==COMMIT_MSG==
Add option to return none on unknown union variants
==COMMIT_MSG==

## Possible downsides?

2023-05-03 00:03 UTC, markgrex commented on conjure_python_client/_serde/decoder.py
> +            if return_none_for_unknown_union_types:
This is the behavior change

2023-05-12 10:51 UTC, johnhany97 requested changes
Just one question, otherwise lgtm!

2023-05-12 10:51 UTC, johnhany97 commented on conjure_python_client/_http/requests_client.py
> +        _return_none_for_unknown_union_types: bool,
Should we default this to False?

2023-05-12 15:05 UTC, markgrex commented on conjure_python_client/_http/requests_client.py
> +        _return_none_for_unknown_union_types: bool,
Good call, updated.

2023-05-13 13:10 UTC, johnhany97 commented
👍

2023-05-13 13:11 UTC, merged

2023-05-13 13:11 UTC, svc-autorelease commented
Released [2.8.0](https://github.com/palantir/conjure-python-client/releases/tag/2.8.0)